version: '3.8'

services:
  resumemaker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
      - ./input:/app/input
      - ./src/resumemaker/crews/poem_crew:/app/src/resumemaker/crews/poem_crew
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env.example
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python", "-m", "resumemaker.crews.poem_crew.data_extraction_crew"]
    # Uncomment the lines below if you need to set API keys
    # env_file:
    #   - .env 