extract_resume_data:
  description: >
    Extract key details from the resume file ({{ resume_file }}) using PDF parsing and text analysis to identify
    the candidate's name, skills, experience, education, and other relevant information.
  expected_output: >
    A structured JSON object containing extracted resume details, including name, skills, job experience,
    education, certifications, projects, and relevant keywords.

extract_linkedin_data:
  description: >
    Scrape the LinkedIn profile at {{ linkedin_url }} to collect publicly available
    professional information, including skills, endorsements, job history, education, and achievements.
    Pay special attention to recommendations, activity, and specific terminology used in descriptions.
  expected_output: >
    A structured JSON dataset containing LinkedIn profile details, such as listed skills (with endorsements),
    work experience (titles, companies, durations), education (degrees, institutions), certifications,
    achievements, and activity patterns.

extract_github_data:
  description: >
    Fetch data from the GitHub profile at {{ github_url }} to extract repositories,
    contributions, programming languages, and relevant project descriptions. Identify the profile's
    overall focus and areas of expertise.
  expected_output: >
    A structured JSON summary of GitHub profile data, including repositories (names, descriptions, stars),
    public contributions summary, primary programming languages, and notable projects.

analyze_github_repositories:
  description: >
    Perform deep analysis of all repositories found in the GitHub profile of {{ candidate_name }}
    at {{ github_url }}. For each repository, analyze code quality, project structure, 
    documentation, technology stack, and implementation patterns. Identify domain expertise
    and programming paradigms the candidate demonstrates.
  expected_output: >
    A comprehensive JSON report detailing each repository's purpose, technologies used, 
    code quality assessment, notable implementation patterns, and the candidate's contributions.
    Include an overall assessment of the candidate's GitHub presence and technical proficiency.

analyze_job_posting:
  description: >
    Process the job description provided at {{ job_posting }} to extract key requirements, 
    skills, experience levels, and industry-specific keywords. Identify both explicit and
    implicit requirements, distinguish between essential and preferred qualifications, and
    extract information about the company culture and work environment.
  expected_output: >
    A structured JSON breakdown of the job posting, detailing required skills (technical and soft),
    experience levels, industry keywords, important qualifications, company culture indicators,
    and role expectations.

compare_resume_with_job:
  description: >
    Compare the extracted resume details with job requirements using
    text analysis to evaluate alignment, detect skill gaps, and provide improvement suggestions.
    Calculate a quantitative match score based on required skills, experience, and qualifications.
    Identify strengths to emphasize and weaknesses to address.
  expected_output: >
    A structured JSON comparison report showing how well the resume matches the job posting, highlighting
    overlapping skills, missing competencies, recommendations for better alignment, and a detailed
    rating score (0-100%) with breakdown by category (skills, experience, education, etc.).

structure_candidate_profile:
  description: >
    Organize extracted data from the resume, LinkedIn, and GitHub
    into a comprehensive candidate profile. Reconcile any discrepancies between sources,
    create a cohesive narrative of the candidate's professional journey, and highlight
    key strengths relevant to the target job. Provide an overall assessment of job fit.
  expected_output: >
    A well-structured JSON candidate profile integrating resume, LinkedIn, and GitHub insights,
    organized into experience, education, skills, projects, certifications, and key achievements.
    Include a job relevance section for ATS optimization, gap analysis, and recommendations
    for profile improvement.