analyze_candidate_profile:
  description: "Analyze the candidate profile JSON to extract skills, experience, education, projects, and certifications, focusing on alignment with the 'AI & Machine Learning Specialist' job posting."
  expected_output: "A detailed analysis of Bishwanath Jana's profile, emphasizing ATS-relevant strengths and keywords like Python, TensorFlow, and NLP."

identify_keywords_for_ats:
  description: "Extract and prioritize ATS keywords from the job posting (e.g., Python, TensorFlow, NLP) and candidate profile, ensuring high optimization for Tech Innovators' requirements."
  expected_output: "A prioritized list of ATS-friendly keywords including Python, TensorFlow, PyTorch, Scikit-learn, SQL, Docker, NLP, and Computer Vision."

craft_resume_sections:
  description: "Craft concise, keyword-rich resume sections (Summary, Skills, Experience, Education, Projects, Certifications) optimized for ATS compatibility with the AI & ML Specialist role."
  expected_output: "ATS-optimized content for all resume sections, integrating matching skills and experience from the candidate profile."

process_profile_image:
  description: "Process the profile image (bishwanath.jpg), ensuring it’s ATS-compatible or excluded if not needed."
  expected_output: "An optimized image file or recommendation to exclude it for ATS compatibility."

create_latex_template:
  description: "Create a simple, ATS-friendly LaTeX template tailored to include Summary, Skills, Experience, Education, Projects, and Certifications."
  expected_output: "A clean, ATS-compatible LaTeX template (.tex) file with a straightforward structure."

generate_latex_resume:
  description: "Generate a LaTeX resume using the candidate profile data, optimized for ATS and tailored to the AI & ML Specialist role."
  expected_output: "A complete, ATS-friendly LaTeX document (.tex) ready for compilation."

compile_final_resume:
  description: "Compile the LaTeX resume into a high ATS-friendly PDF for submission to Tech Innovators."
  expected_output: "A professional, ATS-optimized PDF resume file."